### ISSUE TITLE
testing different language models

### ISSUE THREAD

**Issue by alstn7** [ml-jku/helm#4]
Hi, thanks for the great work!
I am interested in your work and want to test out different language models. 
What part of the code should I tweak to make the adjustment?

Thank you

**Comment by paischer101** [comment]
Thank you for your interest in our work!
The language model is instantiated here:

https://github.com/ml-jku/helm/blob/33d566ed4ad5a12d24b79c99a680a04fc8470c6c/model.py#L106

You can find the available models in huggingface here:

https://huggingface.co/models

Be aware, however, that the handling of the language encoder may differ, due to memory register, etc.

**Comment by alstn7** [comment]
> Thank you for your interest in our work! The language model is instantiated here:
> 
> https://github.com/ml-jku/helm/blob/33d566ed4ad5a12d24b79c99a680a04fc8470c6c/model.py#L106
> 
> You can find the available models in huggingface here:
> 
> https://huggingface.co/models
> 
> Be aware, however, that the handling of the language encoder may differ, due to memory register, etc.

Thank you for your reply!
